//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 3.5.0.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// $ANTLR 3.5.0.2 ADL.g 2015-06-14 19:14:16

// The variable 'variable' is assigned but its value is never used.
#pragma warning disable 219
// Unreachable code detected.
#pragma warning disable 162
// Missing XML comment for publicly visible type or member 'Type_or_Member'
#pragma warning disable 1591
// CLS compliance checking will not be performed on 'type' because it is not visible from outside this assembly.
#pragma warning disable 3019


using adt.ADL;


using System.Collections.Generic;
using Antlr.Runtime;
using Antlr.Runtime.Misc;

namespace  adt 
{
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "3.5.0.2")]
[System.CLSCompliant(false)]
public partial class ADLParser : Antlr.Runtime.Parser
{
	internal static readonly string[] tokenNames = new string[] {
		"<invalid>", "<EOR>", "<DOWN>", "<UP>", "ASTERISK", "ATTRIBUTES", "BASE_CLASS", "CLOSE", "COMMA", "COMMENT", "COMMON_ATTRIBUTES", "DOT", "EQ", "ID", "ID_LETTER", "ID_START_LETTER", "NAMESPACE", "OPEN", "PIPE", "PRINTED", "PRINTER", "QUESTION", "QUOTED_TEXT", "SEMI", "WALKER", "WS"
	};
	public const int EOF=-1;
	public const int ASTERISK=4;
	public const int ATTRIBUTES=5;
	public const int BASE_CLASS=6;
	public const int CLOSE=7;
	public const int COMMA=8;
	public const int COMMENT=9;
	public const int COMMON_ATTRIBUTES=10;
	public const int DOT=11;
	public const int EQ=12;
	public const int ID=13;
	public const int ID_LETTER=14;
	public const int ID_START_LETTER=15;
	public const int NAMESPACE=16;
	public const int OPEN=17;
	public const int PIPE=18;
	public const int PRINTED=19;
	public const int PRINTER=20;
	public const int QUESTION=21;
	public const int QUOTED_TEXT=22;
	public const int SEMI=23;
	public const int WALKER=24;
	public const int WS=25;

	public ADLParser(ITokenStream input)
		: this(input, new RecognizerSharedState())
	{
	}
	public ADLParser(ITokenStream input, RecognizerSharedState state)
		: base(input, state)
	{
		OnCreated();
	}

	public override string[] TokenNames { get { return ADLParser.tokenNames; } }
	public override string GrammarFileName { get { return "ADL.g"; } }


	partial void OnCreated();
	partial void EnterRule(string ruleName, int ruleIndex);
	partial void LeaveRule(string ruleName, int ruleIndex);

	#region Rules
	partial void EnterRule_program();
	partial void LeaveRule_program();
	// $ANTLR start "program"
	// ADL.g:16:8: public program returns [ProgramDecl r] : namespaceDecl baseClassDecl ( walkerDecl )? ( printerDecl )? ( node )+ EOF ;
	[GrammarRule("program")]
	public ProgramDecl program()
	{
		EnterRule_program();
		EnterRule("program", 1);
		TraceIn("program", 1);
		ProgramDecl r = default(ProgramDecl);


		NamespaceDecl namespaceDecl1 = default(NamespaceDecl);
		BaseClassDecl baseClassDecl2 = default(BaseClassDecl);
		WalkerDecl walkerDecl3 = default(WalkerDecl);
		PrinterDecl printerDecl4 = default(PrinterDecl);
		NodeDecl node5 = default(NodeDecl);

		try { DebugEnterRule(GrammarFileName, "program");
		DebugLocation(16, 10);
		try
		{
			// ADL.g:17:5: ( namespaceDecl baseClassDecl ( walkerDecl )? ( printerDecl )? ( node )+ EOF )
			DebugEnterAlt(1);
			// ADL.g:17:7: namespaceDecl baseClassDecl ( walkerDecl )? ( printerDecl )? ( node )+ EOF
			{
			DebugLocation(17, 7);
			PushFollow(Follow._namespaceDecl_in_program57);
			namespaceDecl1=namespaceDecl();
			PopFollow();

			DebugLocation(17, 22);
			 r = new ProgramDecl { ns = namespaceDecl1 }; 
			DebugLocation(18, 5);
			PushFollow(Follow._baseClassDecl_in_program66);
			baseClassDecl2=baseClassDecl();
			PopFollow();

			DebugLocation(18, 19);
			 r.baseClass = baseClassDecl2; 
			DebugLocation(19, 5);
			// ADL.g:19:5: ( walkerDecl )?
			int alt1=2;
			try { DebugEnterSubRule(1);
			try { DebugEnterDecision(1, false);
			int LA1_1 = input.LA(1);

			if ((LA1_1==WALKER))
			{
				alt1 = 1;
			}
			} finally { DebugExitDecision(1); }
			switch (alt1)
			{
			case 1:
				DebugEnterAlt(1);
				// ADL.g:19:6: walkerDecl
				{
				DebugLocation(19, 6);
				PushFollow(Follow._walkerDecl_in_program75);
				walkerDecl3=walkerDecl();
				PopFollow();

				DebugLocation(19, 17);
				 r.walker = walkerDecl3; 

				}
				break;

			}
			} finally { DebugExitSubRule(1); }

			DebugLocation(20, 5);
			// ADL.g:20:5: ( printerDecl )?
			int alt2=2;
			try { DebugEnterSubRule(2);
			try { DebugEnterDecision(2, false);
			int LA2_1 = input.LA(1);

			if ((LA2_1==PRINTER))
			{
				alt2 = 1;
			}
			} finally { DebugExitDecision(2); }
			switch (alt2)
			{
			case 1:
				DebugEnterAlt(1);
				// ADL.g:20:6: printerDecl
				{
				DebugLocation(20, 6);
				PushFollow(Follow._printerDecl_in_program86);
				printerDecl4=printerDecl();
				PopFollow();

				DebugLocation(20, 18);
				 r.printer = printerDecl4; 

				}
				break;

			}
			} finally { DebugExitSubRule(2); }

			DebugLocation(21, 5);
			// ADL.g:21:5: ( node )+
			int cnt3=0;
			try { DebugEnterSubRule(3);
			while (true)
			{
				int alt3=2;
				try { DebugEnterDecision(3, false);
				int LA3_1 = input.LA(1);

				if ((LA3_1==ID))
				{
					alt3 = 1;
				}


				} finally { DebugExitDecision(3); }
				switch (alt3)
				{
				case 1:
					DebugEnterAlt(1);
					// ADL.g:21:6: node
					{
					DebugLocation(21, 6);
					PushFollow(Follow._node_in_program97);
					node5=node();
					PopFollow();

					DebugLocation(22, 9);

					            r.nodes.Add(node5);
					        

					}
					break;

				default:
					if (cnt3 >= 1)
						goto loop3;

					EarlyExitException eee3 = new EarlyExitException( 3, input );
					DebugRecognitionException(eee3);
					throw eee3;
				}
				cnt3++;
			}
			loop3:
				;

			} finally { DebugExitSubRule(3); }

			DebugLocation(25, 8);
			Match(input,EOF,Follow._EOF_in_program116); 

			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("program", 1);
			LeaveRule("program", 1);
			LeaveRule_program();
		}
		DebugLocation(25, 10);
		} finally { DebugExitRule(GrammarFileName, "program"); }
		return r;

	}
	// $ANTLR end "program"

	partial void EnterRule_namespaceDecl();
	partial void LeaveRule_namespaceDecl();
	// $ANTLR start "namespaceDecl"
	// ADL.g:27:1: namespaceDecl returns [NamespaceDecl r] : NAMESPACE id1= ID ( DOT id2= ID )* SEMI ;
	[GrammarRule("namespaceDecl")]
	private NamespaceDecl namespaceDecl()
	{
		EnterRule_namespaceDecl();
		EnterRule("namespaceDecl", 2);
		TraceIn("namespaceDecl", 2);
		NamespaceDecl r = default(NamespaceDecl);


		IToken id1 = default(IToken);
		IToken id2 = default(IToken);

		 r = new NamespaceDecl(); 
		try { DebugEnterRule(GrammarFileName, "namespaceDecl");
		DebugLocation(27, 95);
		try
		{
			// ADL.g:29:5: ( NAMESPACE id1= ID ( DOT id2= ID )* SEMI )
			DebugEnterAlt(1);
			// ADL.g:29:7: NAMESPACE id1= ID ( DOT id2= ID )* SEMI
			{
			DebugLocation(29, 7);
			Match(input,NAMESPACE,Follow._NAMESPACE_in_namespaceDecl137); 
			DebugLocation(29, 20);
			id1=(IToken)Match(input,ID,Follow._ID_in_namespaceDecl141); 
			DebugLocation(29, 24);
			 r.ids.Add((id1!=null?id1.Text:default(string))); 
			DebugLocation(29, 51);
			// ADL.g:29:51: ( DOT id2= ID )*
			try { DebugEnterSubRule(4);
			while (true)
			{
				int alt4=2;
				try { DebugEnterDecision(4, false);
				int LA4_1 = input.LA(1);

				if ((LA4_1==DOT))
				{
					alt4 = 1;
				}


				} finally { DebugExitDecision(4); }
				switch ( alt4 )
				{
				case 1:
					DebugEnterAlt(1);
					// ADL.g:29:52: DOT id2= ID
					{
					DebugLocation(29, 52);
					Match(input,DOT,Follow._DOT_in_namespaceDecl146); 
					DebugLocation(29, 59);
					id2=(IToken)Match(input,ID,Follow._ID_in_namespaceDecl150); 
					DebugLocation(29, 63);
					 r.ids.Add((id2!=null?id2.Text:default(string))); 

					}
					break;

				default:
					goto loop4;
				}
			}

			loop4:
				;

			} finally { DebugExitSubRule(4); }

			DebugLocation(29, 92);
			Match(input,SEMI,Follow._SEMI_in_namespaceDecl156); 

			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("namespaceDecl", 2);
			LeaveRule("namespaceDecl", 2);
			LeaveRule_namespaceDecl();
		}
		DebugLocation(29, 95);
		} finally { DebugExitRule(GrammarFileName, "namespaceDecl"); }
		return r;

	}
	// $ANTLR end "namespaceDecl"

	partial void EnterRule_baseClassDecl();
	partial void LeaveRule_baseClassDecl();
	// $ANTLR start "baseClassDecl"
	// ADL.g:31:1: baseClassDecl returns [BaseClassDecl r] : BASE_CLASS ID SEMI ;
	[GrammarRule("baseClassDecl")]
	private BaseClassDecl baseClassDecl()
	{
		EnterRule_baseClassDecl();
		EnterRule("baseClassDecl", 3);
		TraceIn("baseClassDecl", 3);
		BaseClassDecl r = default(BaseClassDecl);


		IToken ID6 = default(IToken);

		try { DebugEnterRule(GrammarFileName, "baseClassDecl");
		DebugLocation(31, 4);
		try
		{
			// ADL.g:32:5: ( BASE_CLASS ID SEMI )
			DebugEnterAlt(1);
			// ADL.g:32:7: BASE_CLASS ID SEMI
			{
			DebugLocation(32, 7);
			Match(input,BASE_CLASS,Follow._BASE_CLASS_in_baseClassDecl172); 
			DebugLocation(32, 18);
			ID6=(IToken)Match(input,ID,Follow._ID_in_baseClassDecl174); 
			DebugLocation(32, 21);
			Match(input,SEMI,Follow._SEMI_in_baseClassDecl176); 
			DebugLocation(33, 5);
			 r = new BaseClassDecl { name = (ID6!=null?ID6.Text:default(string)) }; 

			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("baseClassDecl", 3);
			LeaveRule("baseClassDecl", 3);
			LeaveRule_baseClassDecl();
		}
		DebugLocation(34, 4);
		} finally { DebugExitRule(GrammarFileName, "baseClassDecl"); }
		return r;

	}
	// $ANTLR end "baseClassDecl"

	partial void EnterRule_walkerDecl();
	partial void LeaveRule_walkerDecl();
	// $ANTLR start "walkerDecl"
	// ADL.g:36:1: walkerDecl returns [WalkerDecl r] : WALKER ID SEMI ;
	[GrammarRule("walkerDecl")]
	private WalkerDecl walkerDecl()
	{
		EnterRule_walkerDecl();
		EnterRule("walkerDecl", 4);
		TraceIn("walkerDecl", 4);
		WalkerDecl r = default(WalkerDecl);


		IToken ID7 = default(IToken);

		try { DebugEnterRule(GrammarFileName, "walkerDecl");
		DebugLocation(36, 4);
		try
		{
			// ADL.g:37:5: ( WALKER ID SEMI )
			DebugEnterAlt(1);
			// ADL.g:37:7: WALKER ID SEMI
			{
			DebugLocation(37, 7);
			Match(input,WALKER,Follow._WALKER_in_walkerDecl203); 
			DebugLocation(37, 14);
			ID7=(IToken)Match(input,ID,Follow._ID_in_walkerDecl205); 
			DebugLocation(37, 17);
			Match(input,SEMI,Follow._SEMI_in_walkerDecl207); 
			DebugLocation(38, 5);
			 r = new WalkerDecl { name = (ID7!=null?ID7.Text:default(string)) }; 

			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("walkerDecl", 4);
			LeaveRule("walkerDecl", 4);
			LeaveRule_walkerDecl();
		}
		DebugLocation(39, 4);
		} finally { DebugExitRule(GrammarFileName, "walkerDecl"); }
		return r;

	}
	// $ANTLR end "walkerDecl"

	partial void EnterRule_printerDecl();
	partial void LeaveRule_printerDecl();
	// $ANTLR start "printerDecl"
	// ADL.g:41:1: printerDecl returns [PrinterDecl r] : PRINTER name= ID root= ID SEMI ;
	[GrammarRule("printerDecl")]
	private PrinterDecl printerDecl()
	{
		EnterRule_printerDecl();
		EnterRule("printerDecl", 5);
		TraceIn("printerDecl", 5);
		PrinterDecl r = default(PrinterDecl);


		IToken name = default(IToken);
		IToken root = default(IToken);

		try { DebugEnterRule(GrammarFileName, "printerDecl");
		DebugLocation(41, 4);
		try
		{
			// ADL.g:42:5: ( PRINTER name= ID root= ID SEMI )
			DebugEnterAlt(1);
			// ADL.g:42:7: PRINTER name= ID root= ID SEMI
			{
			DebugLocation(42, 7);
			Match(input,PRINTER,Follow._PRINTER_in_printerDecl234); 
			DebugLocation(42, 19);
			name=(IToken)Match(input,ID,Follow._ID_in_printerDecl238); 
			DebugLocation(42, 27);
			root=(IToken)Match(input,ID,Follow._ID_in_printerDecl242); 
			DebugLocation(42, 31);
			Match(input,SEMI,Follow._SEMI_in_printerDecl244); 
			DebugLocation(43, 5);
			 r = new PrinterDecl { name = (name!=null?name.Text:default(string)), root = (root!=null?root.Text:default(string)) }; 

			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("printerDecl", 5);
			LeaveRule("printerDecl", 5);
			LeaveRule_printerDecl();
		}
		DebugLocation(44, 4);
		} finally { DebugExitRule(GrammarFileName, "printerDecl"); }
		return r;

	}
	// $ANTLR end "printerDecl"

	partial void EnterRule_node();
	partial void LeaveRule_node();
	// $ANTLR start "node"
	// ADL.g:46:1: node returns [NodeDecl r] : ( nodeVariants | nodeConcrete );
	[GrammarRule("node")]
	private NodeDecl node()
	{
		EnterRule_node();
		EnterRule("node", 6);
		TraceIn("node", 6);
		NodeDecl r = default(NodeDecl);


		NodeVariantsDecl nodeVariants8 = default(NodeVariantsDecl);
		NodeConcreteDecl nodeConcrete9 = default(NodeConcreteDecl);

		try { DebugEnterRule(GrammarFileName, "node");
		DebugLocation(46, 85);
		try
		{
			// ADL.g:47:5: ( nodeVariants | nodeConcrete )
			int alt5=2;
			try { DebugEnterDecision(5, false);
			int LA5_1 = input.LA(1);

			if ((LA5_1==ID))
			{
				int LA5_2 = input.LA(2);

				if ((LA5_2==EQ))
				{
					int LA5_3 = input.LA(3);

					if ((LA5_3==ID))
					{
						int LA5_4 = input.LA(4);

						if ((LA5_4==OPEN))
						{
							alt5 = 1;
						}
						else if (((LA5_4>=ASTERISK && LA5_4<=ATTRIBUTES)||LA5_4==COMMA||LA5_4==ID||LA5_4==QUESTION||LA5_4==SEMI))
						{
							alt5 = 2;
						}
						else
						{
							NoViableAltException nvae = new NoViableAltException("", 5, 3, input, 4);
							DebugRecognitionException(nvae);
							throw nvae;
						}
					}
					else if ((LA5_3==ATTRIBUTES||LA5_3==SEMI))
					{
						alt5 = 2;
					}
					else
					{
						NoViableAltException nvae = new NoViableAltException("", 5, 2, input, 3);
						DebugRecognitionException(nvae);
						throw nvae;
					}
				}
				else
				{
					NoViableAltException nvae = new NoViableAltException("", 5, 1, input, 2);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 5, 0, input, 1);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(5); }
			switch (alt5)
			{
			case 1:
				DebugEnterAlt(1);
				// ADL.g:47:7: nodeVariants
				{
				DebugLocation(47, 7);
				PushFollow(Follow._nodeVariants_in_node271);
				nodeVariants8=nodeVariants();
				PopFollow();

				DebugLocation(47, 20);
				 r = nodeVariants8; 

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// ADL.g:47:48: nodeConcrete
				{
				DebugLocation(47, 48);
				PushFollow(Follow._nodeConcrete_in_node277);
				nodeConcrete9=nodeConcrete();
				PopFollow();

				DebugLocation(47, 61);
				 r = nodeConcrete9; 

				}
				break;

			}
		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("node", 6);
			LeaveRule("node", 6);
			LeaveRule_node();
		}
		DebugLocation(47, 85);
		} finally { DebugExitRule(GrammarFileName, "node"); }
		return r;

	}
	// $ANTLR end "node"

	partial void EnterRule_nodeVariants();
	partial void LeaveRule_nodeVariants();
	// $ANTLR start "nodeVariants"
	// ADL.g:49:1: nodeVariants returns [NodeVariantsDecl r] : ID EQ v1= nodeVariant ( PIPE v2= nodeVariant )* ( common_attributes )? SEMI ;
	[GrammarRule("nodeVariants")]
	private NodeVariantsDecl nodeVariants()
	{
		EnterRule_nodeVariants();
		EnterRule("nodeVariants", 7);
		TraceIn("nodeVariants", 7);
		NodeVariantsDecl r = default(NodeVariantsDecl);


		IToken ID10 = default(IToken);
		NodeVariantDecl v1 = default(NodeVariantDecl);
		NodeVariantDecl v2 = default(NodeVariantDecl);
		List<AttributeDecl> common_attributes11 = default(List<AttributeDecl>);

		try { DebugEnterRule(GrammarFileName, "nodeVariants");
		DebugLocation(49, 8);
		try
		{
			// ADL.g:50:5: ( ID EQ v1= nodeVariant ( PIPE v2= nodeVariant )* ( common_attributes )? SEMI )
			DebugEnterAlt(1);
			// ADL.g:50:7: ID EQ v1= nodeVariant ( PIPE v2= nodeVariant )* ( common_attributes )? SEMI
			{
			DebugLocation(50, 7);
			ID10=(IToken)Match(input,ID,Follow._ID_in_nodeVariants299); 
			DebugLocation(50, 10);
			Match(input,EQ,Follow._EQ_in_nodeVariants301); 
			DebugLocation(50, 13);
			 r = new NodeVariantsDecl { id = (ID10!=null?ID10.Text:default(string)) }; 
			DebugLocation(51, 7);
			PushFollow(Follow._nodeVariant_in_nodeVariants311);
			v1=nodeVariant();
			PopFollow();

			DebugLocation(51, 20);
			 r.variants.Add(v1); 
			DebugLocation(51, 48);
			// ADL.g:51:48: ( PIPE v2= nodeVariant )*
			try { DebugEnterSubRule(6);
			while (true)
			{
				int alt6=2;
				try { DebugEnterDecision(6, false);
				int LA6_1 = input.LA(1);

				if ((LA6_1==PIPE))
				{
					alt6 = 1;
				}


				} finally { DebugExitDecision(6); }
				switch ( alt6 )
				{
				case 1:
					DebugEnterAlt(1);
					// ADL.g:51:49: PIPE v2= nodeVariant
					{
					DebugLocation(51, 49);
					Match(input,PIPE,Follow._PIPE_in_nodeVariants316); 
					DebugLocation(51, 56);
					PushFollow(Follow._nodeVariant_in_nodeVariants320);
					v2=nodeVariant();
					PopFollow();

					DebugLocation(51, 69);
					 r.variants.Add(v2); 

					}
					break;

				default:
					goto loop6;
				}
			}

			loop6:
				;

			} finally { DebugExitSubRule(6); }

			DebugLocation(52, 5);
			// ADL.g:52:5: ( common_attributes )?
			int alt7=2;
			try { DebugEnterSubRule(7);
			try { DebugEnterDecision(7, false);
			int LA7_1 = input.LA(1);

			if ((LA7_1==COMMON_ATTRIBUTES))
			{
				alt7 = 1;
			}
			} finally { DebugExitDecision(7); }
			switch (alt7)
			{
			case 1:
				DebugEnterAlt(1);
				// ADL.g:52:5: common_attributes
				{
				DebugLocation(52, 5);
				PushFollow(Follow._common_attributes_in_nodeVariants330);
				common_attributes11=common_attributes();
				PopFollow();


				}
				break;

			}
			} finally { DebugExitSubRule(7); }

			DebugLocation(53, 5);

			        r.attributes = common_attributes11 ?? new List<AttributeDecl>();
			    
			DebugLocation(56, 5);
			Match(input,SEMI,Follow._SEMI_in_nodeVariants343); 

			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("nodeVariants", 7);
			LeaveRule("nodeVariants", 7);
			LeaveRule_nodeVariants();
		}
		DebugLocation(56, 8);
		} finally { DebugExitRule(GrammarFileName, "nodeVariants"); }
		return r;

	}
	// $ANTLR end "nodeVariants"

	partial void EnterRule_nodeVariant();
	partial void LeaveRule_nodeVariant();
	// $ANTLR start "nodeVariant"
	// ADL.g:58:1: nodeVariant returns [NodeVariantDecl r] : ID OPEN ( fields )? CLOSE ( attributes )? ;
	[GrammarRule("nodeVariant")]
	private NodeVariantDecl nodeVariant()
	{
		EnterRule_nodeVariant();
		EnterRule("nodeVariant", 8);
		TraceIn("nodeVariant", 8);
		NodeVariantDecl r = default(NodeVariantDecl);


		IToken ID12 = default(IToken);
		List<FieldDecl> fields13 = default(List<FieldDecl>);
		List<AttributeDecl> attributes14 = default(List<AttributeDecl>);

		try { DebugEnterRule(GrammarFileName, "nodeVariant");
		DebugLocation(58, 4);
		try
		{
			// ADL.g:59:5: ( ID OPEN ( fields )? CLOSE ( attributes )? )
			DebugEnterAlt(1);
			// ADL.g:59:7: ID OPEN ( fields )? CLOSE ( attributes )?
			{
			DebugLocation(59, 7);
			ID12=(IToken)Match(input,ID,Follow._ID_in_nodeVariant359); 
			DebugLocation(59, 10);
			Match(input,OPEN,Follow._OPEN_in_nodeVariant361); 
			DebugLocation(59, 15);
			// ADL.g:59:15: ( fields )?
			int alt8=2;
			try { DebugEnterSubRule(8);
			try { DebugEnterDecision(8, false);
			int LA8_1 = input.LA(1);

			if ((LA8_1==ID))
			{
				alt8 = 1;
			}
			} finally { DebugExitDecision(8); }
			switch (alt8)
			{
			case 1:
				DebugEnterAlt(1);
				// ADL.g:59:15: fields
				{
				DebugLocation(59, 15);
				PushFollow(Follow._fields_in_nodeVariant363);
				fields13=fields();
				PopFollow();


				}
				break;

			}
			} finally { DebugExitSubRule(8); }

			DebugLocation(59, 23);
			Match(input,CLOSE,Follow._CLOSE_in_nodeVariant366); 
			DebugLocation(59, 29);
			// ADL.g:59:29: ( attributes )?
			int alt9=2;
			try { DebugEnterSubRule(9);
			try { DebugEnterDecision(9, false);
			int LA9_1 = input.LA(1);

			if ((LA9_1==ATTRIBUTES))
			{
				alt9 = 1;
			}
			} finally { DebugExitDecision(9); }
			switch (alt9)
			{
			case 1:
				DebugEnterAlt(1);
				// ADL.g:59:29: attributes
				{
				DebugLocation(59, 29);
				PushFollow(Follow._attributes_in_nodeVariant368);
				attributes14=attributes();
				PopFollow();


				}
				break;

			}
			} finally { DebugExitSubRule(9); }

			DebugLocation(60, 4);
			 r = new NodeVariantDecl 
			       { id = (ID12!=null?ID12.Text:default(string)),
			        fields = fields13 ?? new List<FieldDecl>(),
			        attributes = attributes14 ?? new List<AttributeDecl>()
			       };
			   

			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("nodeVariant", 8);
			LeaveRule("nodeVariant", 8);
			LeaveRule_nodeVariant();
		}
		DebugLocation(65, 4);
		} finally { DebugExitRule(GrammarFileName, "nodeVariant"); }
		return r;

	}
	// $ANTLR end "nodeVariant"

	partial void EnterRule_nodeConcrete();
	partial void LeaveRule_nodeConcrete();
	// $ANTLR start "nodeConcrete"
	// ADL.g:67:1: nodeConcrete returns [NodeConcreteDecl r] : ID EQ ( fields )? ( attributes )? SEMI ;
	[GrammarRule("nodeConcrete")]
	private NodeConcreteDecl nodeConcrete()
	{
		EnterRule_nodeConcrete();
		EnterRule("nodeConcrete", 9);
		TraceIn("nodeConcrete", 9);
		NodeConcreteDecl r = default(NodeConcreteDecl);


		IToken ID15 = default(IToken);
		List<FieldDecl> fields16 = default(List<FieldDecl>);
		List<AttributeDecl> attributes17 = default(List<AttributeDecl>);

		try { DebugEnterRule(GrammarFileName, "nodeConcrete");
		DebugLocation(67, 9);
		try
		{
			// ADL.g:68:5: ( ID EQ ( fields )? ( attributes )? SEMI )
			DebugEnterAlt(1);
			// ADL.g:68:7: ID EQ ( fields )? ( attributes )? SEMI
			{
			DebugLocation(68, 7);
			ID15=(IToken)Match(input,ID,Follow._ID_in_nodeConcrete390); 
			DebugLocation(68, 10);
			Match(input,EQ,Follow._EQ_in_nodeConcrete392); 
			DebugLocation(68, 13);
			// ADL.g:68:13: ( fields )?
			int alt10=2;
			try { DebugEnterSubRule(10);
			try { DebugEnterDecision(10, false);
			int LA10_1 = input.LA(1);

			if ((LA10_1==ID))
			{
				alt10 = 1;
			}
			} finally { DebugExitDecision(10); }
			switch (alt10)
			{
			case 1:
				DebugEnterAlt(1);
				// ADL.g:68:13: fields
				{
				DebugLocation(68, 13);
				PushFollow(Follow._fields_in_nodeConcrete394);
				fields16=fields();
				PopFollow();


				}
				break;

			}
			} finally { DebugExitSubRule(10); }

			DebugLocation(68, 21);
			// ADL.g:68:21: ( attributes )?
			int alt11=2;
			try { DebugEnterSubRule(11);
			try { DebugEnterDecision(11, false);
			int LA11_1 = input.LA(1);

			if ((LA11_1==ATTRIBUTES))
			{
				alt11 = 1;
			}
			} finally { DebugExitDecision(11); }
			switch (alt11)
			{
			case 1:
				DebugEnterAlt(1);
				// ADL.g:68:21: attributes
				{
				DebugLocation(68, 21);
				PushFollow(Follow._attributes_in_nodeConcrete397);
				attributes17=attributes();
				PopFollow();


				}
				break;

			}
			} finally { DebugExitSubRule(11); }

			DebugLocation(69, 4);
			 r = new NodeConcreteDecl 
			       { id = (ID15!=null?ID15.Text:default(string)),
			        fields = fields16 ?? new List<FieldDecl>(),
			        attributes = attributes17 ?? new List<AttributeDecl>()
			       };
			   
			DebugLocation(74, 6);
			Match(input,SEMI,Follow._SEMI_in_nodeConcrete405); 

			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("nodeConcrete", 9);
			LeaveRule("nodeConcrete", 9);
			LeaveRule_nodeConcrete();
		}
		DebugLocation(74, 9);
		} finally { DebugExitRule(GrammarFileName, "nodeConcrete"); }
		return r;

	}
	// $ANTLR end "nodeConcrete"

	partial void EnterRule_fields();
	partial void LeaveRule_fields();
	// $ANTLR start "fields"
	// ADL.g:76:1: fields returns [List<FieldDecl> r] : f1= field ( COMMA f2= field )* ;
	[GrammarRule("fields")]
	private List<FieldDecl> fields()
	{
		EnterRule_fields();
		EnterRule("fields", 10);
		TraceIn("fields", 10);
		List<FieldDecl> r = default(List<FieldDecl>);


		FieldDecl f1 = default(FieldDecl);
		FieldDecl f2 = default(FieldDecl);

		 r = new List<FieldDecl>(); 
		try { DebugEnterRule(GrammarFileName, "fields");
		DebugLocation(76, 70);
		try
		{
			// ADL.g:78:5: (f1= field ( COMMA f2= field )* )
			DebugEnterAlt(1);
			// ADL.g:78:7: f1= field ( COMMA f2= field )*
			{
			DebugLocation(78, 9);
			PushFollow(Follow._field_in_fields432);
			f1=field();
			PopFollow();

			DebugLocation(78, 16);
			 r.Add(f1); 
			DebugLocation(78, 35);
			// ADL.g:78:35: ( COMMA f2= field )*
			try { DebugEnterSubRule(12);
			while (true)
			{
				int alt12=2;
				try { DebugEnterDecision(12, false);
				int LA12_1 = input.LA(1);

				if ((LA12_1==COMMA))
				{
					alt12 = 1;
				}


				} finally { DebugExitDecision(12); }
				switch ( alt12 )
				{
				case 1:
					DebugEnterAlt(1);
					// ADL.g:78:36: COMMA f2= field
					{
					DebugLocation(78, 36);
					Match(input,COMMA,Follow._COMMA_in_fields437); 
					DebugLocation(78, 44);
					PushFollow(Follow._field_in_fields441);
					f2=field();
					PopFollow();

					DebugLocation(78, 51);
					 r.Add(f2); 

					}
					break;

				default:
					goto loop12;
				}
			}

			loop12:
				;

			} finally { DebugExitSubRule(12); }


			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("fields", 10);
			LeaveRule("fields", 10);
			LeaveRule_fields();
		}
		DebugLocation(78, 70);
		} finally { DebugExitRule(GrammarFileName, "fields"); }
		return r;

	}
	// $ANTLR end "fields"

	partial void EnterRule_attributes();
	partial void LeaveRule_attributes();
	// $ANTLR start "attributes"
	// ADL.g:80:1: attributes returns [List<AttributeDecl> r] : ATTRIBUTES a1= attributeDecl ( COMMA a2= attributeDecl )* ;
	[GrammarRule("attributes")]
	private List<AttributeDecl> attributes()
	{
		EnterRule_attributes();
		EnterRule("attributes", 11);
		TraceIn("attributes", 11);
		List<AttributeDecl> r = default(List<AttributeDecl>);


		AttributeDecl a1 = default(AttributeDecl);
		AttributeDecl a2 = default(AttributeDecl);

		 r = new List<AttributeDecl>(); 
		try { DebugEnterRule(GrammarFileName, "attributes");
		DebugLocation(80, 97);
		try
		{
			// ADL.g:82:5: ( ATTRIBUTES a1= attributeDecl ( COMMA a2= attributeDecl )* )
			DebugEnterAlt(1);
			// ADL.g:82:7: ATTRIBUTES a1= attributeDecl ( COMMA a2= attributeDecl )*
			{
			DebugLocation(82, 7);
			Match(input,ATTRIBUTES,Follow._ATTRIBUTES_in_attributes466); 
			DebugLocation(82, 20);
			PushFollow(Follow._attributeDecl_in_attributes470);
			a1=attributeDecl();
			PopFollow();

			DebugLocation(82, 35);
			 r.Add(a1); 
			DebugLocation(82, 54);
			// ADL.g:82:54: ( COMMA a2= attributeDecl )*
			try { DebugEnterSubRule(13);
			while (true)
			{
				int alt13=2;
				try { DebugEnterDecision(13, false);
				int LA13_1 = input.LA(1);

				if ((LA13_1==COMMA))
				{
					alt13 = 1;
				}


				} finally { DebugExitDecision(13); }
				switch ( alt13 )
				{
				case 1:
					DebugEnterAlt(1);
					// ADL.g:82:55: COMMA a2= attributeDecl
					{
					DebugLocation(82, 55);
					Match(input,COMMA,Follow._COMMA_in_attributes475); 
					DebugLocation(82, 63);
					PushFollow(Follow._attributeDecl_in_attributes479);
					a2=attributeDecl();
					PopFollow();

					DebugLocation(82, 78);
					 r.Add(a2); 

					}
					break;

				default:
					goto loop13;
				}
			}

			loop13:
				;

			} finally { DebugExitSubRule(13); }


			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("attributes", 11);
			LeaveRule("attributes", 11);
			LeaveRule_attributes();
		}
		DebugLocation(82, 97);
		} finally { DebugExitRule(GrammarFileName, "attributes"); }
		return r;

	}
	// $ANTLR end "attributes"

	partial void EnterRule_common_attributes();
	partial void LeaveRule_common_attributes();
	// $ANTLR start "common_attributes"
	// ADL.g:84:1: common_attributes returns [List<AttributeDecl> r] : COMMON_ATTRIBUTES a1= attributeDecl ( COMMA a2= attributeDecl )* ;
	[GrammarRule("common_attributes")]
	private List<AttributeDecl> common_attributes()
	{
		EnterRule_common_attributes();
		EnterRule("common_attributes", 12);
		TraceIn("common_attributes", 12);
		List<AttributeDecl> r = default(List<AttributeDecl>);


		AttributeDecl a1 = default(AttributeDecl);
		AttributeDecl a2 = default(AttributeDecl);

		 r = new List<AttributeDecl>(); 
		try { DebugEnterRule(GrammarFileName, "common_attributes");
		DebugLocation(84, 104);
		try
		{
			// ADL.g:86:5: ( COMMON_ATTRIBUTES a1= attributeDecl ( COMMA a2= attributeDecl )* )
			DebugEnterAlt(1);
			// ADL.g:86:7: COMMON_ATTRIBUTES a1= attributeDecl ( COMMA a2= attributeDecl )*
			{
			DebugLocation(86, 7);
			Match(input,COMMON_ATTRIBUTES,Follow._COMMON_ATTRIBUTES_in_common_attributes504); 
			DebugLocation(86, 27);
			PushFollow(Follow._attributeDecl_in_common_attributes508);
			a1=attributeDecl();
			PopFollow();

			DebugLocation(86, 42);
			 r.Add(a1); 
			DebugLocation(86, 61);
			// ADL.g:86:61: ( COMMA a2= attributeDecl )*
			try { DebugEnterSubRule(14);
			while (true)
			{
				int alt14=2;
				try { DebugEnterDecision(14, false);
				int LA14_1 = input.LA(1);

				if ((LA14_1==COMMA))
				{
					alt14 = 1;
				}


				} finally { DebugExitDecision(14); }
				switch ( alt14 )
				{
				case 1:
					DebugEnterAlt(1);
					// ADL.g:86:62: COMMA a2= attributeDecl
					{
					DebugLocation(86, 62);
					Match(input,COMMA,Follow._COMMA_in_common_attributes513); 
					DebugLocation(86, 70);
					PushFollow(Follow._attributeDecl_in_common_attributes517);
					a2=attributeDecl();
					PopFollow();

					DebugLocation(86, 85);
					 r.Add(a2); 

					}
					break;

				default:
					goto loop14;
				}
			}

			loop14:
				;

			} finally { DebugExitSubRule(14); }


			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("common_attributes", 12);
			LeaveRule("common_attributes", 12);
			LeaveRule_common_attributes();
		}
		DebugLocation(86, 104);
		} finally { DebugExitRule(GrammarFileName, "common_attributes"); }
		return r;

	}
	// $ANTLR end "common_attributes"

	partial void EnterRule_field();
	partial void LeaveRule_field();
	// $ANTLR start "field"
	// ADL.g:88:1: field returns [FieldDecl r] : typeId= ID (q= QUESTION |a= ASTERISK )? (nameId= ID )? ;
	[GrammarRule("field")]
	private FieldDecl field()
	{
		EnterRule_field();
		EnterRule("field", 13);
		TraceIn("field", 13);
		FieldDecl r = default(FieldDecl);


		IToken typeId = default(IToken);
		IToken q = default(IToken);
		IToken a = default(IToken);
		IToken nameId = default(IToken);

		try { DebugEnterRule(GrammarFileName, "field");
		DebugLocation(88, 5);
		try
		{
			// ADL.g:89:5: (typeId= ID (q= QUESTION |a= ASTERISK )? (nameId= ID )? )
			DebugEnterAlt(1);
			// ADL.g:89:7: typeId= ID (q= QUESTION |a= ASTERISK )? (nameId= ID )?
			{
			DebugLocation(89, 13);
			typeId=(IToken)Match(input,ID,Follow._ID_in_field543); 
			DebugLocation(89, 17);
			// ADL.g:89:17: (q= QUESTION |a= ASTERISK )?
			int alt15=3;
			try { DebugEnterSubRule(15);
			try { DebugEnterDecision(15, false);
			int LA15_1 = input.LA(1);

			if ((LA15_1==QUESTION))
			{
				alt15 = 1;
			}
			else if ((LA15_1==ASTERISK))
			{
				alt15 = 2;
			}
			} finally { DebugExitDecision(15); }
			switch (alt15)
			{
			case 1:
				DebugEnterAlt(1);
				// ADL.g:89:18: q= QUESTION
				{
				DebugLocation(89, 19);
				q=(IToken)Match(input,QUESTION,Follow._QUESTION_in_field548); 

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// ADL.g:89:29: a= ASTERISK
				{
				DebugLocation(89, 30);
				a=(IToken)Match(input,ASTERISK,Follow._ASTERISK_in_field552); 

				}
				break;

			}
			} finally { DebugExitSubRule(15); }

			DebugLocation(89, 48);
			// ADL.g:89:48: (nameId= ID )?
			int alt16=2;
			try { DebugEnterSubRule(16);
			try { DebugEnterDecision(16, false);
			int LA16_1 = input.LA(1);

			if ((LA16_1==ID))
			{
				alt16 = 1;
			}
			} finally { DebugExitDecision(16); }
			switch (alt16)
			{
			case 1:
				DebugEnterAlt(1);
				// ADL.g:89:48: nameId= ID
				{
				DebugLocation(89, 48);
				nameId=(IToken)Match(input,ID,Follow._ID_in_field558); 

				}
				break;

			}
			} finally { DebugExitSubRule(16); }

			DebugLocation(89, 53);

			    r = new FieldDecl {
			    type = (typeId!=null?typeId.Text:default(string)), id = (nameId!=null?nameId.Text:default(string)) ?? (typeId!=null?typeId.Text:default(string)), optional = q != null, many = a != null    };
			    

			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("field", 13);
			LeaveRule("field", 13);
			LeaveRule_field();
		}
		DebugLocation(92, 5);
		} finally { DebugExitRule(GrammarFileName, "field"); }
		return r;

	}
	// $ANTLR end "field"

	partial void EnterRule_attributeDecl();
	partial void LeaveRule_attributeDecl();
	// $ANTLR start "attributeDecl"
	// ADL.g:94:1: attributeDecl returns [AttributeDecl r] : ( PRINTED )? attrType ID ;
	[GrammarRule("attributeDecl")]
	private AttributeDecl attributeDecl()
	{
		EnterRule_attributeDecl();
		EnterRule("attributeDecl", 14);
		TraceIn("attributeDecl", 14);
		AttributeDecl r = default(AttributeDecl);


		IToken ID18 = default(IToken);
		IToken PRINTED20 = default(IToken);
		string attrType19 = default(string);

		try { DebugEnterRule(GrammarFileName, "attributeDecl");
		DebugLocation(94, 120);
		try
		{
			// ADL.g:95:5: ( ( PRINTED )? attrType ID )
			DebugEnterAlt(1);
			// ADL.g:95:7: ( PRINTED )? attrType ID
			{
			DebugLocation(95, 7);
			// ADL.g:95:7: ( PRINTED )?
			int alt17=2;
			try { DebugEnterSubRule(17);
			try { DebugEnterDecision(17, false);
			int LA17_1 = input.LA(1);

			if ((LA17_1==PRINTED))
			{
				alt17 = 1;
			}
			} finally { DebugExitDecision(17); }
			switch (alt17)
			{
			case 1:
				DebugEnterAlt(1);
				// ADL.g:95:7: PRINTED
				{
				DebugLocation(95, 7);
				PRINTED20=(IToken)Match(input,PRINTED,Follow._PRINTED_in_attributeDecl577); 

				}
				break;

			}
			} finally { DebugExitSubRule(17); }

			DebugLocation(95, 16);
			PushFollow(Follow._attrType_in_attributeDecl580);
			attrType19=attrType();
			PopFollow();

			DebugLocation(95, 25);
			ID18=(IToken)Match(input,ID,Follow._ID_in_attributeDecl582); 
			DebugLocation(95, 28);
			 r = new AttributeDecl { id = (ID18!=null?ID18.Text:default(string)), type = attrType19, printed = PRINTED20 != null }; 

			}

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("attributeDecl", 14);
			LeaveRule("attributeDecl", 14);
			LeaveRule_attributeDecl();
		}
		DebugLocation(95, 120);
		} finally { DebugExitRule(GrammarFileName, "attributeDecl"); }
		return r;

	}
	// $ANTLR end "attributeDecl"

	partial void EnterRule_attrType();
	partial void LeaveRule_attrType();
	// $ANTLR start "attrType"
	// ADL.g:97:1: attrType returns [string r] : (id1= ID ( DOT id2= ID )* | QUOTED_TEXT );
	[GrammarRule("attrType")]
	private string attrType()
	{
		EnterRule_attrType();
		EnterRule("attrType", 15);
		TraceIn("attrType", 15);
		string r = default(string);


		IToken id1 = default(IToken);
		IToken id2 = default(IToken);
		IToken QUOTED_TEXT21 = default(IToken);

		try { DebugEnterRule(GrammarFileName, "attrType");
		DebugLocation(97, 88);
		try
		{
			// ADL.g:98:5: (id1= ID ( DOT id2= ID )* | QUOTED_TEXT )
			int alt19=2;
			try { DebugEnterDecision(19, false);
			int LA19_1 = input.LA(1);

			if ((LA19_1==ID))
			{
				alt19 = 1;
			}
			else if ((LA19_1==QUOTED_TEXT))
			{
				alt19 = 2;
			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 19, 0, input, 1);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(19); }
			switch (alt19)
			{
			case 1:
				DebugEnterAlt(1);
				// ADL.g:98:7: id1= ID ( DOT id2= ID )*
				{
				DebugLocation(98, 10);
				id1=(IToken)Match(input,ID,Follow._ID_in_attrType602); 
				DebugLocation(98, 14);
				 r = (id1!=null?id1.Text:default(string)); 
				DebugLocation(98, 34);
				// ADL.g:98:34: ( DOT id2= ID )*
				try { DebugEnterSubRule(18);
				while (true)
				{
					int alt18=2;
					try { DebugEnterDecision(18, false);
					int LA18_1 = input.LA(1);

					if ((LA18_1==DOT))
					{
						alt18 = 1;
					}


					} finally { DebugExitDecision(18); }
					switch ( alt18 )
					{
					case 1:
						DebugEnterAlt(1);
						// ADL.g:98:35: DOT id2= ID
						{
						DebugLocation(98, 35);
						Match(input,DOT,Follow._DOT_in_attrType607); 
						DebugLocation(98, 42);
						id2=(IToken)Match(input,ID,Follow._ID_in_attrType611); 
						DebugLocation(98, 46);
						 r = r + "." + (id2!=null?id2.Text:default(string)); 

						}
						break;

					default:
						goto loop18;
					}
				}

				loop18:
					;

				} finally { DebugExitSubRule(18); }


				}
				break;
			case 2:
				DebugEnterAlt(2);
				// ADL.g:99:7: QUOTED_TEXT
				{
				DebugLocation(99, 7);
				QUOTED_TEXT21=(IToken)Match(input,QUOTED_TEXT,Follow._QUOTED_TEXT_in_attrType623); 
				DebugLocation(99, 19);
				 r = (QUOTED_TEXT21!=null?QUOTED_TEXT21.Text:default(string)).Substring(1, (QUOTED_TEXT21!=null?QUOTED_TEXT21.Text:default(string)).Length - 2); 

				}
				break;

			}
		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		}
		finally
		{
			TraceOut("attrType", 15);
			LeaveRule("attrType", 15);
			LeaveRule_attrType();
		}
		DebugLocation(99, 88);
		} finally { DebugExitRule(GrammarFileName, "attrType"); }
		return r;

	}
	// $ANTLR end "attrType"
	#endregion Rules


	#region Follow sets
	private static class Follow
	{
		public static readonly BitSet _namespaceDecl_in_program57 = new BitSet(new ulong[]{0x40UL});
		public static readonly BitSet _baseClassDecl_in_program66 = new BitSet(new ulong[]{0x1102000UL});
		public static readonly BitSet _walkerDecl_in_program75 = new BitSet(new ulong[]{0x102000UL});
		public static readonly BitSet _printerDecl_in_program86 = new BitSet(new ulong[]{0x2000UL});
		public static readonly BitSet _node_in_program97 = new BitSet(new ulong[]{0x0UL});
		public static readonly BitSet _EOF_in_program116 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _NAMESPACE_in_namespaceDecl137 = new BitSet(new ulong[]{0x2000UL});
		public static readonly BitSet _ID_in_namespaceDecl141 = new BitSet(new ulong[]{0x800800UL});
		public static readonly BitSet _DOT_in_namespaceDecl146 = new BitSet(new ulong[]{0x2000UL});
		public static readonly BitSet _ID_in_namespaceDecl150 = new BitSet(new ulong[]{0x800800UL});
		public static readonly BitSet _SEMI_in_namespaceDecl156 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _BASE_CLASS_in_baseClassDecl172 = new BitSet(new ulong[]{0x2000UL});
		public static readonly BitSet _ID_in_baseClassDecl174 = new BitSet(new ulong[]{0x800000UL});
		public static readonly BitSet _SEMI_in_baseClassDecl176 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _WALKER_in_walkerDecl203 = new BitSet(new ulong[]{0x2000UL});
		public static readonly BitSet _ID_in_walkerDecl205 = new BitSet(new ulong[]{0x800000UL});
		public static readonly BitSet _SEMI_in_walkerDecl207 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _PRINTER_in_printerDecl234 = new BitSet(new ulong[]{0x2000UL});
		public static readonly BitSet _ID_in_printerDecl238 = new BitSet(new ulong[]{0x2000UL});
		public static readonly BitSet _ID_in_printerDecl242 = new BitSet(new ulong[]{0x800000UL});
		public static readonly BitSet _SEMI_in_printerDecl244 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _nodeVariants_in_node271 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _nodeConcrete_in_node277 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _ID_in_nodeVariants299 = new BitSet(new ulong[]{0x1000UL});
		public static readonly BitSet _EQ_in_nodeVariants301 = new BitSet(new ulong[]{0x2000UL});
		public static readonly BitSet _nodeVariant_in_nodeVariants311 = new BitSet(new ulong[]{0x840400UL});
		public static readonly BitSet _PIPE_in_nodeVariants316 = new BitSet(new ulong[]{0x2000UL});
		public static readonly BitSet _nodeVariant_in_nodeVariants320 = new BitSet(new ulong[]{0x840400UL});
		public static readonly BitSet _common_attributes_in_nodeVariants330 = new BitSet(new ulong[]{0x800000UL});
		public static readonly BitSet _SEMI_in_nodeVariants343 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _ID_in_nodeVariant359 = new BitSet(new ulong[]{0x20000UL});
		public static readonly BitSet _OPEN_in_nodeVariant361 = new BitSet(new ulong[]{0x2080UL});
		public static readonly BitSet _fields_in_nodeVariant363 = new BitSet(new ulong[]{0x80UL});
		public static readonly BitSet _CLOSE_in_nodeVariant366 = new BitSet(new ulong[]{0x22UL});
		public static readonly BitSet _attributes_in_nodeVariant368 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _ID_in_nodeConcrete390 = new BitSet(new ulong[]{0x1000UL});
		public static readonly BitSet _EQ_in_nodeConcrete392 = new BitSet(new ulong[]{0x802020UL});
		public static readonly BitSet _fields_in_nodeConcrete394 = new BitSet(new ulong[]{0x800020UL});
		public static readonly BitSet _attributes_in_nodeConcrete397 = new BitSet(new ulong[]{0x800000UL});
		public static readonly BitSet _SEMI_in_nodeConcrete405 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _field_in_fields432 = new BitSet(new ulong[]{0x102UL});
		public static readonly BitSet _COMMA_in_fields437 = new BitSet(new ulong[]{0x2000UL});
		public static readonly BitSet _field_in_fields441 = new BitSet(new ulong[]{0x102UL});
		public static readonly BitSet _ATTRIBUTES_in_attributes466 = new BitSet(new ulong[]{0x482000UL});
		public static readonly BitSet _attributeDecl_in_attributes470 = new BitSet(new ulong[]{0x102UL});
		public static readonly BitSet _COMMA_in_attributes475 = new BitSet(new ulong[]{0x482000UL});
		public static readonly BitSet _attributeDecl_in_attributes479 = new BitSet(new ulong[]{0x102UL});
		public static readonly BitSet _COMMON_ATTRIBUTES_in_common_attributes504 = new BitSet(new ulong[]{0x482000UL});
		public static readonly BitSet _attributeDecl_in_common_attributes508 = new BitSet(new ulong[]{0x102UL});
		public static readonly BitSet _COMMA_in_common_attributes513 = new BitSet(new ulong[]{0x482000UL});
		public static readonly BitSet _attributeDecl_in_common_attributes517 = new BitSet(new ulong[]{0x102UL});
		public static readonly BitSet _ID_in_field543 = new BitSet(new ulong[]{0x202012UL});
		public static readonly BitSet _QUESTION_in_field548 = new BitSet(new ulong[]{0x2002UL});
		public static readonly BitSet _ASTERISK_in_field552 = new BitSet(new ulong[]{0x2002UL});
		public static readonly BitSet _ID_in_field558 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _PRINTED_in_attributeDecl577 = new BitSet(new ulong[]{0x402000UL});
		public static readonly BitSet _attrType_in_attributeDecl580 = new BitSet(new ulong[]{0x2000UL});
		public static readonly BitSet _ID_in_attributeDecl582 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _ID_in_attrType602 = new BitSet(new ulong[]{0x802UL});
		public static readonly BitSet _DOT_in_attrType607 = new BitSet(new ulong[]{0x2000UL});
		public static readonly BitSet _ID_in_attrType611 = new BitSet(new ulong[]{0x802UL});
		public static readonly BitSet _QUOTED_TEXT_in_attrType623 = new BitSet(new ulong[]{0x2UL});
	}
	#endregion Follow sets
}

} // namespace  adt 
